spring:
  jpa:
    generate-ddl: true
  datasource:
    url: 'jdbc:postgresql://localhost:5432/sweeter'
    username: serhiimaltsev
    password: 1234567890
    driver-class-name: org.postgresql.Driver
  mustache:
    servlet:
      expose-request-attributes: true